name: flavorfinder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0' # Adjusted to a version compatible with your Flutter SDK

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_animate: ^1.0.0
  table_calendar: ^3.0.1
  flutter_svg: ^0.22.0
  device_preview: ^1.2.0
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_charts: ^0.2.0
  syncfusion_flutter_charts: ^20.1.54 # Updated version to ensure compatibility

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/placeholder.webp
  - assets/logo.png
  - assets/Pasta.jpg
  - assets/Chicken.jpg
  - assets/coconut-sambal.jpg
  - assets/curry.png
  - assets/fish.jpg
  - assets/Hoppers.jpeg
  - assets/breakfast.jpg
  - assets/desserts.jpeg
  - assets/DietPlans.jpg
  - assets/dinner.webp
  - assets/FoodRecipes.jpg
  - assets/HealthTips.jpg
  - assets/Kottu.jpg
  - assets/lamprais.jpg
  - assets/lunch.jpg
  - assets/Milk-Rice.jpg
  - assets/NutritionTracking.jpg
  - assets/snacks.jpg
  - assets/Watalappam.jpg


